# Generated by Django 5.2.7 on 2026-05-06 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия лекций",
                "verbose_name_plural": "Сессии лекций",
            },
        ),
        migrations.CreateModel(
            name="CompletedTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=500, verbose_name="Тема")),
                ("lecture_text", models.TextField(verbose_name="Текст лекции")),
                ("feedback", models.TextField(verbose_name="Фидбэк от ИИ")),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_topics",
                        to="lecture.lecturesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Завершенная тема",
                "verbose_name_plural": "Завершенные темы",
            },
        ),
    ]
