# Generated by Django 5.2.7 on 2026-05-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturesession",
            name="current_feedback",
            field=models.TextField(blank=True, verbose_name="Последний фидбэк"),
        ),
        migrations.AddField(
            model_name="lecturesession",
            name="current_lecture_text",
            field=models.TextField(blank=True, verbose_name="Черновик лекции"),
        ),
        migrations.AddField(
            model_name="lecturesession",
            name="current_topic",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Текущая тема"
            ),
        ),
    ]
